
export const FETCH_COLLECTIONS = "FETCH_COLLECTIONS";
export const FETCH_SINGLE_COLLECTIONS = "FETCH_SINGLE_COLLECTIONS";
export const SET_LOADING = "SET_LOADING";
export const SET_ERROR = "SET_ERROR";
export const SORT_BY_SEARCH = "SORT_BY_SEARCH";
